import React, { Component } from 'react';
import {BrowserRouter,Route,Link} from 'react-router-dom';
class Main extends Component{
    render(){
        return(
            <BrowserRouter>
                <div className="container" style={{height:"500px"}}>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                    <p>bakchodi</p>
                </div>
            </BrowserRouter>
        )
    }
}
export default Main;